### ISSUE TITLE
Invalid access to private name

### ISSUE THREAD

**Issue by eventualbuddha** [thlorenz/es6ify#3]
I get this error whenever I require es6ify and anything else that includes the es6ify runtime.js. Sample output:

```
Running "browserify:dist" (browserify) task
>> Bundled tmp/math.es5.js

Running "concat:dist" (concat) task
File "dist/math.js" created.

Running "require-math" task
Warning: Invalid access to private name Use --force to continue.

Aborted due to warnings.
```

See [this sample project](https://github.com/eventualbuddha/es6ify-name-invalid-access-bug) for a reproducible test case.

**Comment by thlorenz** [comment]
Has this problem been resolved for you?
I looked at your sample but it is hard to tell what is actually going on since it's all configured via grunt metadata.

If you still have issues please provide an example that uses a simple script to build your bundle (similar to the es6ify example itself -- see Readme).

Thanks.

**Comment by kof** [comment]
please update traceur to fix this issue ...

**Comment by kof** [comment]
to reproduce just require es6-module-transpiler and es6ify

**Comment by thlorenz** [comment]
@kof not sure what issue you are referring to. 
Loading runtime or private name access?

Please give more info, i.e. what got fixed in traceur, what version of traceur has the fix, etc.

**Comment by kof** [comment]
/XXX/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:201
      throw Error('Invalid access to private name');
            ^
Error: Invalid access to private name
    at Error (<anonymous>)
    at assertNotName (/XXX/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:201:13)
    at defineProperty (/XXX/node_modules/es6-module-transpiler/dist/es6-module-transpiler.js:256:7)
    at new Name (eval at <anonymous> (/XXX/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:109:5)
    at eval (eval at <anonymous> (/XXX/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:130:27)
    at eval (eval at <anonymous> (/XXX/node_modules/traceur/src/node/traceur.js:24:17), <anonymous>:422:3)
    at eval (native)
    at Object.<anonymous> (/XXX/node_modules/traceur/src/node/traceur.js:24:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
make: **\* [build] Error 8

**Comment by kof** [comment]
98250080e33f1bde7383c4fdd5584571712a4485

**Comment by kof** [comment]
however I have tried to install the latest traceur and removed local one, so the latest one was used and the issue remains

**Comment by thlorenz** [comment]
Ok, so the link you provided seems to be broken.
Also I'm not sure what you are saying, does the newest traceur (or which version?) fix your problem?

Cuz if it doesn't, es6ify cannot fix it.

If it does, is what you are requesting an upgrade to the latest traceur version?

Either way, maybe a pull request would make things clearer. Just perform the changes you would want to see and we can go from there. Please make sure all tests pass `npm test`.

**Comment by kof** [comment]
I read comments on traceur project and thought it will fix the problem, but it hasn't fixed it for me.

**Comment by thlorenz** [comment]
> however I have tried to install the latest traceur and removed local one

does that mean you removed the `./es6ify/node_modules/traceur`? Cause changing the globally installed one wouldn't affect es6ify. If however you managed to make `es6ify` use the newest traceur and it is still not fixed, then the problem is still with traceur.

In that case please file an issue there and investigate what the status is.
